/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.doctor;

import javax.swing.JOptionPane;

/**
 *
 * @author vinaykumargudooru
 */
public class PoliceDashboard extends javax.swing.JFrame {

    /**
     * Creates new form PoliceDashboardd
     */
    public PoliceDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mHome = new javax.swing.JMenu();
        mtProfile = new javax.swing.JMenuItem();
        mHospital = new javax.swing.JMenu();
        mtAdmissions = new javax.swing.JMenuItem();
        mExit = new javax.swing.JMenu();
        mtLogout = new javax.swing.JMenuItem();
        mtExitApp = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(340, 130));

        mHome.setText("Home");

        mtProfile.setText("Profile");
        mtProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtProfileActionPerformed(evt);
            }
        });
        mHome.add(mtProfile);

        jMenuBar1.add(mHome);

        mHospital.setText("Hospital");

        mtAdmissions.setText("Admissions");
        mtAdmissions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtAdmissionsActionPerformed(evt);
            }
        });
        mHospital.add(mtAdmissions);

        jMenuBar1.add(mHospital);

        mExit.setText("Exit");

        mtLogout.setText("Logout");
        mtLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtLogoutActionPerformed(evt);
            }
        });
        mExit.add(mtLogout);

        mtExitApp.setText("Exit Application");
        mtExitApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtExitAppActionPerformed(evt);
            }
        });
        mExit.add(mtExitApp);

        jMenuBar1.add(mExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mtExitAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtExitAppActionPerformed
        // TODO add your handling code here:
        int exitAction = JOptionPane.showConfirmDialog(null,"Do you want to close application","Select",JOptionPane.YES_NO_OPTION);
        if(exitAction==0){
           System.exit(0);
        }
    }//GEN-LAST:event_mtExitAppActionPerformed

    private void mtLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtLogoutActionPerformed
        // TODO add your handling code here:
        int logoutAction = JOptionPane.showConfirmDialog(null,"Do you want to logout","Select",JOptionPane.YES_NO_OPTION);
        if(logoutAction==0){
            setVisible(false);
            new PoliceLoginPage().setVisible(true);
        }
    }//GEN-LAST:event_mtLogoutActionPerformed

    private void mtProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtProfileActionPerformed
        // TODO add your handling code here:
        new PoliceProfile().setVisible(true);
        
    }//GEN-LAST:event_mtProfileActionPerformed

    private void mtAdmissionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtAdmissionsActionPerformed
        // TODO add your handling code here:
        new PoliceHospitalAdmissions().setVisible(true);
    }//GEN-LAST:event_mtAdmissionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoliceDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoliceDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoliceDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoliceDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoliceDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mExit;
    private javax.swing.JMenu mHome;
    private javax.swing.JMenu mHospital;
    private javax.swing.JMenuItem mtAdmissions;
    private javax.swing.JMenuItem mtExitApp;
    private javax.swing.JMenuItem mtLogout;
    private javax.swing.JMenuItem mtProfile;
    // End of variables declaration//GEN-END:variables
}
