package ui.sponsors;

import businessFramework.Environment;
import businessFramework.commonFunctions.Sponsorship;
import businessFramework.commonFunctions.IntegerFieldValidation;
import businessFramework.commonFunctions.MobileNoValidation;
import businessFramework.commonFunctions.StringValidation;
import businessFramework.commonFunctions.Validations;
import businessFramework.organizations.ManagerOrganizations;
import businessFramework.userAccount.User;
import businessFramework.requestPipeline.SponsorshipRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jhalaksurve
 */
public class DonationJPanelWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private User userAccount;
    private Environment ecoSystem;
   
    /**
     * Creates new form DonationJPanelWorkArea
     */
    public DonationJPanelWorkArea(JPanel userProcessContainer, User userAccount, Environment ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
        addInputVerifiers();
        toAccntNumberField.setText(Sponsorship.toAccNo);
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth();
        int h = getHeight();
        
         Color c1 = new Color(210,240,114);
         Color c2 = new Color(210,240,114);
         
        GradientPaint gp = new GradientPaint(w/4, 0, c2, w/4, h, c1);
        setOpaque( false );
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
        setOpaque( true );
    }
    
      private void addInputVerifiers() {
        InputVerifier noValidation = new IntegerFieldValidation();
        amountField.setInputVerifier(noValidation);
        monthField.setInputVerifier(noValidation);
        yearField.setInputVerifier(noValidation);
        
        InputVerifier phnumberValidation = new MobileNoValidation();
        cardNumberField.setInputVerifier(phnumberValidation);
        
         
        InputVerifier stringValidation = new StringValidation();
        nameTxtField.setInputVerifier(stringValidation);
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEnt = new javax.swing.JLabel();
        helpName = new javax.swing.JLabel();
        cardNumberField = new javax.swing.JTextField();
        expiryDate = new javax.swing.JLabel();
        monthField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        toAccntNumber = new javax.swing.JLabel();
        toAccntNumberField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        manageEnt.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        manageEnt.setText("Make Donation ");

        helpName.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        helpName.setText("Enter Card Number (10 Digits)");

        expiryDate.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        expiryDate.setText("Enter Expiry Date(MM/YYYY)");

        amount.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        amount.setText("Enter Amount");

        submitBtn.setBackground(new java.awt.Color(0, 153, 153));
        submitBtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(0, 153, 153));
        cancelBtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        name.setText("Enter Name");

        toAccntNumber.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        toAccntNumber.setText("To Account Number");

        toAccntNumberField.setEditable(false);
        toAccntNumberField.setBackground(new java.awt.Color(204, 255, 204));
        toAccntNumberField.setEnabled(false);

        backJButton.setBackground(new java.awt.Color(0, 153, 153));
        backJButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< back");
        backJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 344, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(helpName)
                            .addComponent(amount)
                            .addComponent(name)
                            .addComponent(expiryDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTxtField)
                            .addComponent(amountField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(312, 312, 312))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(manageEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(toAccntNumber)
                                .addGap(18, 18, 18)
                                .addComponent(toAccntNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(manageEnt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toAccntNumber)
                    .addComponent(toAccntNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpName)
                    .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDate)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(cancelBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backJButton)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
       if(nameTxtField.getText().trim().isEmpty() || 
               cardNumberField.getText().length()>10 || 
               monthField.getText().length()>2 || 
               yearField.getText().length()>4 || amountField.getText().length()<0)
       {
        JOptionPane.showMessageDialog(null, "Please enter valid input!", "warning",JOptionPane.WARNING_MESSAGE);
        return;       
       }
       try
       {
       int month = Integer.parseInt(monthField.getText());
       int year = Integer.parseInt(yearField.getText());
       if(month<0 || month > 12)
       {
       JOptionPane.showMessageDialog(null, "Please enter month between 1 and 12!", "warning",JOptionPane.WARNING_MESSAGE);
        return;     
       }
       if(year<2015 || year>2050)
       {
        JOptionPane.showMessageDialog(null, "Please enter valid expiry year!", "warning",JOptionPane.WARNING_MESSAGE);
        return;       
       }
      
       DateFormat df = new SimpleDateFormat("EEE, MMM d, YYYY hh:mm aaa");
       Calendar cal = Calendar.getInstance();
       String timestamp = df.format(cal.getTime());
       
       Sponsorship sponsorship = userAccount.getPerson().addDonation();
       
       sponsorship.setAmount(amountField.getText());
       sponsorship.setSponsoredDate(timestamp);
       sponsorship.setAccName(nameTxtField.getText());
       sponsorship.setAccNumber(cardNumberField.getText());
      
           try
           {
           SponsorshipRequest sponsorshipRequest = new SponsorshipRequest();
           sponsorshipRequest.setDonation(sponsorship);
           sponsorshipRequest.setSponsoredBy(userAccount.getName());
           sponsorshipRequest.setSenderDetails(userAccount);
           sponsorshipRequest.setRequestDate(new Date());
           sponsorshipRequest.setReqMessage("Donated Money");
           
           userAccount.getRequestPipeline().getRequestList().add(sponsorshipRequest);
           
           User ua = getHeartHelpManagerAccnt();
           if(ua==null)
           {
            JOptionPane.showMessageDialog(null, "Please verify if heart help manager acccount exists!", "warning",JOptionPane.WARNING_MESSAGE);
           userAccount.getRequestPipeline().getRequestList().remove(sponsorshipRequest);  
            return;   
           }
           if(ua!=null)
           {
            sponsorshipRequest.setReceiver(ua);
            sponsorshipRequest.setResolveDate(new Date());
            ua.getRequestPipeline().getRequestList().add(sponsorshipRequest); 
            sponsorshipRequest.setStatus("Completed");
           JOptionPane.showMessageDialog(null, "Donation has been made successfully, Thank You", "success",JOptionPane.PLAIN_MESSAGE);
            }
           else
           {
           userAccount.getRequestPipeline().getRequestList().remove(sponsorshipRequest);  
           }
           }
           catch(Exception e)
            {
           JOptionPane.showMessageDialog(null, "Please verify if heart help manager acccount exists!", "warning",JOptionPane.WARNING_MESSAGE);
           return;      
            }
        resetFields();
      }
       catch(Exception e)
       {
      JOptionPane.showMessageDialog(null, "Please enter valid data!", "warning",JOptionPane.WARNING_MESSAGE);
       return;      
       }
    }//GEN-LAST:event_submitBtnActionPerformed
    
    public User getHeartHelpManagerAccnt()
    {
        try
        {
        ManagerOrganizations managerOrganization = (ManagerOrganizations)Validations.getManagerOrganizations(ecoSystem, userAccount);
        User mngrAccnt = null;
        if(managerOrganization==null)
        {
        JOptionPane.showMessageDialog(null, "Supervisor Organization does not exist!", "warning",JOptionPane.WARNING_MESSAGE);
        return mngrAccnt;  
        }
      
        for(User ua : managerOrganization.getUserDirectory().getUserList())
        {
            
         if((ua.getRole().toString()).equals("HeartHelpManagerRole"))  
         {
          mngrAccnt = ua;   
         }
        }
        return mngrAccnt;
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, "Please verify if Supervisor organization exist!", "warning",JOptionPane.WARNING_MESSAGE);
        
        return null;      
        }
   
    }
    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
       resetFields();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    public void resetFields()
    {
     cardNumberField.setText("");
     monthField.setText("");
     yearField.setText("");
     amountField.setText("");
     nameTxtField.setText("");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cardNumberField;
    private javax.swing.JLabel expiryDate;
    private javax.swing.JLabel helpName;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JTextField monthField;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel toAccntNumber;
    private javax.swing.JTextField toAccntNumberField;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}
